CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT,
CADASTRO VARCHAR(255),
PAGAMENTO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTO(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
PRECO DOUBLE,
CONTROLADO VARCHAR(255),
QUANTIDADE INT,
PRIMARY KEY(ID),
CATEGORIA_ID BIGINT,
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
);

SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PRODUTO;

INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("SIM", "DEBITO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("SIM", "CREDITO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("NÃO", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("SIM", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CADASTRO, PAGAMENTO) VALUE ("NÃO", "DEBITO");

INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('Dipirona', 22.93, 'não', 1, 1);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('ibuprofeno', 15.64, 'não', 2 , 3);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('Dipirona', 22.93, 'não', 6 , 2);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('​Amprenavir', 73.45, 'sim', 3, 4);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('creme de cabelo', 7.00, 'não', 1, 5);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('​Aripiprazol', 65.90, 'sim', 2, 2);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('creme dental', 10.90, 'não', 1, 3);
INSERT INTO TB_PRODUTO (NOME, PRECO, CONTROLADO, QUANTIDADE, CATEGORIA_ID) VALUES ('Dipirona', 22.93, 'não', 4, 4);

SELECT*FROM TB_PRODUTO WHERE PRECO > 50.00;
SELECT*FROM TB_PRODUTO WHERE PRECO >= 5.00 && VALOR <=60.00;
