CREATE DATABASE DB_CIDADE_DOS_VEGETAIS;

USE DB_CIDADE_DOS_VEGETAIS;

CREATE TABLE TB_CATEGORIA(
ID BIGINT AUTO_INCREMENT,
CPF_NOTA VARCHAR(255),
PAGAMENTO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PRODUTO(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
PRECO DOUBLE,
PESO VARCHAR(255),
QUANTIDADE INT,
PRIMARY KEY(ID),
CATEGORIA_ID BIGINT,
FOREIGN KEY (CATEGORIA_ID) REFERENCES TB_CATEGORIA(ID)
);

SELECT * FROM TB_CATEGORIA;
SELECT * FROM TB_PRODUTO;

INSERT INTO TB_CATEGORIA (CPF_NOTA, PAGAMENTO) VALUE ("SIM", "DEBITO");
INSERT INTO TB_CATEGORIA (CPF_NOTA, PAGAMENTO) VALUE ("SIM", "CREDITO");
INSERT INTO TB_CATEGORIA (CPF_NOTA, PAGAMENTO) VALUE ("NÃO", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CPF_NOTA, PAGAMENTO) VALUE ("SIM", "DINHEIRO");
INSERT INTO TB_CATEGORIA (CPF_NOTA, PAGAMENTO) VALUE ("NÃO", "DEBITO");
