CREATE DATABASE IF NOT EXISTS DB_SERVICO_HR;

USE DB_SERVICO_HR;

CREATE TABLE  TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
CARGO VARCHAR(255),
NUMERO_ROUPA VARCHAR(225),
SALARIO DOUBLE,
PRIMARY KEY(ID)
);

