CREATE DATABASE IF NOT EXISTS DB_SERVICO_HR;

USE DB_SERVICO_HR;

CREATE TABLE  TB_FUNCIONARIOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
CARGO VARCHAR(255),
NUMERO_ROUPA VARCHAR(225),
SALARIO DOUBLE,
PRIMARY KEY(ID)
);

SELECT * FROM TB_FUNCIONARIOS;

INSERT INTO TB_FUNCIONARIOS (NOME, CARGO, NUMERO_ROUPA, SALARIO) VALUES ('Nicole','Gerente','M',8600.00);
INSERT INTO TB_FUNCIONARIOS (NOME, CARGO, NUMERO_ROUPA, SALARIO) VALUES ('Rafel','assistente de RH','P',2000.00);
INSERT INTO TB_FUNCIONARIOS (NOME, CARGO, NUMERO_ROUPA, SALARIO) VALUES ('Paula','faxineira','P',2200.00);
INSERT INTO TB_FUNCIONARIOS (NOME, CARGO, NUMERO_ROUPA, SALARIO) VALUES ('Anthonio','Tecnico em informatica','G',2300.00);
INSERT INTO TB_FUNCIONARIOS (NOME, CARGO, NUMERO_ROUPA, SALARIO) VALUES ('Victor','chefe','M',50000.00);

select * from TB_FUNCIONARIOS where SALARIO > 2000;
select * from tb_funcionarios where SALARIO < 2000;