CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
CADASTRADO VARCHAR(255),
ENDEREÇO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
SABOR VARCHAR(255),
BORDA VARCHAR(255),
TAMANHO VARCHAR(255),
VALOR DOUBLE,
PRIMARY KEY(ID),
USUARIO_ID BIGINT,
FOREIGN KEY (USUARIO_ID) REFERENCES TB_CATEGORIAS(ID)
);

