CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
CADASTRADO VARCHAR(255),
ENDEREÇO VARCHAR(255),
PRIMARY KEY(ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
SABOR VARCHAR(255),
BORDA VARCHAR(255),
TAMANHO VARCHAR(255),
VALOR DOUBLE,
PRIMARY KEY(ID),
USUARIO_ID BIGINT,
FOREIGN KEY (USUARIO_ID) REFERENCES TB_CATEGORIAS(ID)
);

SELECT*FROM TB_CATEGORIAS;
SELECT*FROM TB_PIZZAS;

INSERT INTO TB_CATEGORIAS (CADASTRADO, ENDEREÇO) VALUES ('sim', 'av.america, 492');
INSERT INTO TB_CATEGORIAS (CADASTRADO, ENDEREÇO) VALUES ('sim', 'rua santana, 382');
INSERT INTO TB_CATEGORIAS (CADASTRADO, ENDEREÇO) VALUES ('não', 'rua almeida, 271');
INSERT INTO TB_CATEGORIAS (CADASTRADO, ENDEREÇO) VALUES ('não', 'rua tucuruvi, 281');
INSERT INTO TB_CATEGORIAS (CADASTRADO, ENDEREÇO) VALUES ('sim', 'rua sargitariana, 252');

INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Calabresa', 'chedar', 16.90, 'mini', 1);
INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Portuguesa', 'catupiry', 20.00 , 'pequeno', 3);
INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Marguerita', 'chedar', 35.90, 'grande', 2);
INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Frango com catupiry', 'chedar', 29.90, 'média', 4);
INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Muçarela', 'chedar', 52.75, 'familia', 5);
INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Napolitana', 'catupiry', 29.90, 'média', 2);
INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Brigadeiro', 'Nutella', 52.75, 'familia', 3);
INSERT INTO TB_PIZZAS (SABOR, BORDA, VALOR, TAMANHO, USUARIO_ID) VALUES ('Califórnia', 'catupiry', 52.75, 'familia', 4);

