CREATE DATABASE IF NOT EXISTS DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_PRODUTOS (
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
CATEGORIA VARCHAR(255),
COR VARCHAR(255),
VALOR DOUBLE,
PRIMARY KEY(ID)
);


